### ISSUE TITLE
Incorrect verification source after deleting

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#623]
To reproduce

1. Validate using eidas or bank
3. Add a role at an institution
4. Remove the role

The name displayed is as validated by the institution, but the label shows it's validated by eherkenning.

![image](https://github.com/user-attachments/assets/8e919b4f-0282-44f6-975a-808d661f7c4b)

Expected Behaviour:
- If the user has an externaly validated account, and a role is added, the user is asked if he want's to use the new names as validated names for services
- Is the preferred validation is removed, use the names last added validation method for the preferred names.
- Always display the source of the names in the overview's "validated by" field

**Comment by Tyskai** [comment]
Unfortunately this problem is not fixed. Or even created a new problem (related to 630)

1. Validate using eidas
2. Add a role at an institution, click "no, do not use"

Expected: the information of the user has "eherkenning" and the eIDAS name
Actual behaviour: the information of the user has "example.com" = the institution, while having the eIDAS name

![Screenshot 2024-10-28 at 19 16 41](https://github.com/user-attachments/assets/b7f27fe9-9da4-4fc1-89a2-6a51c23611e4)

**Comment by oharsta** [comment]
Added test in https://github.com/OpenConext/OpenConext-myconext/commit/919235e9017dcc407d9c7ff274f8a299bdbdd5d2. Moving to to-be-tested

**Comment by Tyskai** [comment]
Tested again! Now all my test cases seem to work!
